In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('studentscores.csv')

In [3]:
dataset.isnull().sum()

Hours     0
Scores    0
dtype: int64

In [4]:
x = dataset.iloc[ : ,   : 1 ].values
y = dataset.iloc[ : , 1 ].values

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(x, y, test_size=.30, random_state=1)

In [7]:
xtest

array([[1.1],
       [3.3],
       [1.9],
       [8.5],
       [4.8],
       [7.7],
       [6.1],
       [7.4]])

In [8]:
ytest

array([17, 42, 24, 75, 54, 85, 67, 69], dtype=int64)

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
model = LinearRegression()

In [11]:
model.fit(xtrain,ytrain)

LinearRegression()

In [12]:
model.predict(xtest)

array([ 9.93952968, 32.84320126, 18.26813752, 86.97915227, 48.45934097,
       78.65054442, 61.99332873, 75.52731648])

In [13]:
model.score(xtest, ytest)

0.8933827573294114